openapi: "3.0.0"
info:
  version: 1.0.0
  title: Empik Demo API
servers:
  - url: http://localhost:7113/
tags:
  - name: Users
paths:
  /api/users:
    get:
      tags:
        - Users
      operationId: getUser
      summary: Get user
      description: Get user information
      parameters:
        - in: query
          name: login
          required: true
          description: "User login"
          schema:
            type: string
      responses:
        200:
          description: User parameter
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponseDTO'
        400:
          description: Bad request
          content:
            application/text:
              schema:
                type: string
        404:
          description: Not found
          content:
            application/text:
              schema:
                type: string
        500:
          description: Internal Server Error
          content:
            application/text:
              schema:
                type: string
components:
  schemas:
    UserResponseDTO:
      type: object
      properties:
        id:
          type: string
        login:
          type: string
        name:
          type: string
        type:
          type: string
        created_at:
          type: string
          format: date-time
        avatar_url:
          type: string
        calculations:
          type: number
          format: float

